// Regenerates src/models.ts from the upstream Neon AI Gateway catalog.
// Usage: npm run update-models
//
// The generated file owns NEON_MODELS and MODEL_CAPABILITIES. src/stream.ts
// reads MODEL_CAPABILITIES at request time, so upstream contract changes land
// here instead of in hand-coded branches.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const MODELS_URL = "https://neon.com/models.json";

export interface UpstreamModel {
	id: string;
	name?: string;
	family?: string;
	reasoning?: boolean;
	tool_call?: boolean;
	temperature?: boolean;
	modalities?: { input?: string[] };
	limit?: { context?: number; output?: number };
	cost?: { input?: number; output?: number };
}

interface NeonModelInput {
	id: string;
	name: string;
	reasoning: boolean;
	input: ("text" | "image")[];
	context: number;
	output: number;
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
}

/** pi-ai models are chat models; embedding families never enter the catalog. */
export function isChatModel(model: UpstreamModel): boolean {
	return !/embedding/i.test(model.family ?? "");
}

const PI_INPUT = new Set(["text", "image"]);

/** Map an upstream entry onto the chat-model shape pi expects. */
export function toNeonModelInput(model: UpstreamModel): NeonModelInput {
	return {
		id: model.id,
		name: model.name ?? model.id,
		reasoning: model.reasoning === true,
		input: (model.modalities?.input ?? ["text"]).filter((m): m is "text" | "image" => PI_INPUT.has(m)),
		context: model.limit?.context ?? 0,
		output: model.limit?.output ?? 0,
		cost: {
			input: model.cost?.input ?? 0,
			output: model.cost?.output ?? 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
	};
}

function fmt(n: number): string {
	return n >= 10_000 ? n.toLocaleString("en-US").replace(/,/g, "_") : String(n);
}

function entrySource(entry: NeonModelInput): string {
	return [
		"\tm({",
		`\t\tid: ${JSON.stringify(entry.id)},`,
		`\t\tname: ${JSON.stringify(entry.name)},`,
		`\t\treasoning: ${entry.reasoning},`,
		`\t\tinput: [${entry.input.map((i) => JSON.stringify(i)).join(", ")}],`,
		`\t\tcontext: ${fmt(entry.context)},`,
		`\t\toutput: ${fmt(entry.output)},`,
		`\t\tcost: { input: ${entry.cost.input}, output: ${entry.cost.output}, cacheRead: 0, cacheWrite: 0 },`,
		"\t}),",
	].join("\n");
}

function capabilitySource(id: string, model: UpstreamModel): string {
	const temperature = model.temperature === true;
	const toolCall = model.tool_call === true;
	return `\t${JSON.stringify(id)}: { temperature: ${temperature}, toolCall: ${toolCall} },`;
}

export function buildModelsSource(models: UpstreamModel[]): string {
	const chat = models.filter(isChatModel).map(toNeonModelInput).sort((a, b) => a.id.localeCompare(b.id));
	const capEntries = chat
		.map((entry) => {
			const upstream = models.find((m) => m.id === entry.id);
			return capabilitySource(entry.id, upstream as UpstreamModel);
		})
		.join("\n");

	return `// Generated by scripts/update-models.ts from ${MODELS_URL}.
// Regenerate with \`npm run update-models\`. Do not edit by hand.
//
// Costs are USD per million tokens. cacheRead/cacheWrite are not published
// upstream and default to 0.

import type { Model } from "@earendil-works/pi-ai";

type Api = "openai-completions";

interface NeonModelInput {
	id: string;
	name: string;
	reasoning: boolean;
	input: ("text" | "image")[];
	context: number;
	output: number;
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
}

function m(entry: NeonModelInput): Model<Api> {
	return {
		id: entry.id,
		name: entry.name,
		api: "openai-completions",
		provider: "neon",
		baseUrl: "https://placeholder.invalid/v1",
		reasoning: entry.reasoning,
		input: entry.input,
		cost: entry.cost,
		contextWindow: entry.context,
		maxTokens: entry.output,
	};
}

export const NEON_MODELS: Model<"openai-completions">[] = [
${chat.map(entrySource).join("\n")}
];

export interface NeonModelCapabilities {
	/** Upstream marks the model as rejecting the temperature sampling parameter. */
	temperature: boolean;
	/** Upstream marks the model as supporting function tools. */
	toolCall: boolean;
}

/** Per-model gateway contract from the upstream catalog, keyed by model id. */
export const MODEL_CAPABILITIES: Record<string, NeonModelCapabilities> = {
${capEntries}
};

const MODEL_IDS = new Set(NEON_MODELS.map((model) => canonicalModelId(model.id)));

export function canonicalModelId(id: string): string {
	const lower = id.toLowerCase();
	return lower.startsWith("databricks-") ? lower.slice("databricks-".length) : lower;
}

export function isKnownNeonModel(id: string): boolean {
	return MODEL_IDS.has(canonicalModelId(id));
}
`;
}

async function main(): Promise<void> {
	const response = await fetch(MODELS_URL, {
		headers: { "User-Agent": "pi-provider-neon-ai-gateway-update-models" },
	});
	if (!response.ok) throw new Error(`Failed to fetch ${MODELS_URL}: ${response.status}`);
	const payload = (await response.json()) as {
		neon?: { models?: Record<string, UpstreamModel> | UpstreamModel[] };
	};
	const raw = payload.neon?.models;
	const models: UpstreamModel[] = Array.isArray(raw)
		? raw
		: raw
			? Object.entries(raw).map(([id, model]) => ({ id, ...(model as object) }))
			: [];
	const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "models.ts");
	writeFileSync(outPath, buildModelsSource(models));
	console.log(`Wrote ${outPath} with ${models.filter(isChatModel).length} chat models (from ${models.length} upstream entries).`);
}

const invokedDirectly =
	process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) {
	await main();
}
